container:
  image: python:slim

lint_task:
  setup_script:
    - pip install flake8==3.5.0
    - pip install codespell==1.15.0
  script:
    - PYTHONWARNINGS="ignore" flake8 --ignore=E501,F841,W503 --exclude=xmrswap/contrib,.eggs
    - codespell --check-filenames --disable-colors --quiet-level=7 --ignore-words=tests/lint/spelling.ignore-words.txt -S contrib,.git,.eggs,*.pyc

test_task:
  setup_script:
    - export TEST_DATADIRS=~/test/
    - export BIN_DIRS=~/binaries
    - export PARTICL_BINDIR=${BIN_DIRS}/particl-${PART_VERSION}/bin
    - export BITCOIN_BINDIR=${BIN_DIRS}/bitcoin-${BTC_VERSION}/bin
    - export XMR_BINDIR=${BIN_DIRS}/monero-x86_64-linux-gnu-v${XMR_VERSION}
    - if [ ! -d "$BIN_DIRS" ]; then mkdir -p "$BIN_DIRS" ; fi
    - if [ ! -d "$PARTICL_BINDIR" ]; then cd "$BIN_DIRS" && wget https://github.com/tecnovert/particl-core/releases/download/v${PART_VERSION}/particl-${PART_VERSION}-x86_64-linux-gnu.tar.gz && tar xvf particl-${PART_VERSION}-x86_64-linux-gnu.tar.gz; fi
    - if [ ! -d "$BITCOIN_BINDIR" ]; then cd "$BIN_DIRS" && wget https://bitcoincore.org/bin/bitcoin-core-${BTC_VERSION}/bitcoin-${BTC_VERSION}-x86_64-linux-gnu.tar.gz && tar xvf bitcoin-${BTC_VERSION}-x86_64-linux-gnu.tar.gz; fi
    - if [ ! -d "$XMR_BINDIR" ]; then cd "$BIN_DIRS" && wget https://downloads.getmonero.org/cli/monero-linux-x64-${XMR_VERSION}.tar.bz2 && tar xvf monero-linux-x64-${XMR_VERSION}.tar.bz2; fi
  script:
    - cd "${CIRRUS_WORKING_DIR}"
    - python setup.py test
